######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 11 21:01:37 2012
######################################################################

DESDIR = bin

SOURCES = src/main.cc
INCLUDE = include

# Directories
